services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: urlcompressor
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: UrlCompressor
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: